apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-manifest
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: registry.gitlab.com/nonlucratif/terraform-k8s-gitlabci-datascientest
          ports:
            - containerPort: 80
