apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-manifest
  labels:
    app: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
        - name: webapp1
          image: registry.gitlab.com/nonlucratif/terraform-k8s-gitlabci-datascientest:master
          ports:
            - containerPort: 80
